# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nathan/Documents/odrive-communication-speed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nathan/Documents/odrive-communication-speed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nathan/Documents/odrive-communication-speed/CMakeFiles /Users/nathan/Documents/odrive-communication-speed/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nathan/Documents/odrive-communication-speed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named odrive_c_sdk

# Build rule for target.
odrive_c_sdk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 odrive_c_sdk
.PHONY : odrive_c_sdk

# fast build rule for target.
odrive_c_sdk/fast:
	$(MAKE) -f CMakeFiles/odrive_c_sdk.dir/build.make CMakeFiles/odrive_c_sdk.dir/build
.PHONY : odrive_c_sdk/fast

#=============================================================================
# Target rules for targets named odrive_cpp_sdk

# Build rule for target.
odrive_cpp_sdk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 odrive_cpp_sdk
.PHONY : odrive_cpp_sdk

# fast build rule for target.
odrive_cpp_sdk/fast:
	$(MAKE) -f CMakeFiles/odrive_cpp_sdk.dir/build.make CMakeFiles/odrive_cpp_sdk.dir/build
.PHONY : odrive_cpp_sdk/fast

#=============================================================================
# Target rules for targets named c_sdk_test

# Build rule for target.
c_sdk_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c_sdk_test
.PHONY : c_sdk_test

# fast build rule for target.
c_sdk_test/fast:
	$(MAKE) -f CMakeFiles/c_sdk_test.dir/build.make CMakeFiles/c_sdk_test.dir/build
.PHONY : c_sdk_test/fast

#=============================================================================
# Target rules for targets named odrive_test

# Build rule for target.
odrive_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 odrive_test
.PHONY : odrive_test

# fast build rule for target.
odrive_test/fast:
	$(MAKE) -f CMakeFiles/odrive_test.dir/build.make CMakeFiles/odrive_test.dir/build
.PHONY : odrive_test/fast

src/c_sdk_test.o: src/c_sdk_test.cpp.o

.PHONY : src/c_sdk_test.o

# target to build an object file
src/c_sdk_test.cpp.o:
	$(MAKE) -f CMakeFiles/c_sdk_test.dir/build.make CMakeFiles/c_sdk_test.dir/src/c_sdk_test.cpp.o
.PHONY : src/c_sdk_test.cpp.o

src/c_sdk_test.i: src/c_sdk_test.cpp.i

.PHONY : src/c_sdk_test.i

# target to preprocess a source file
src/c_sdk_test.cpp.i:
	$(MAKE) -f CMakeFiles/c_sdk_test.dir/build.make CMakeFiles/c_sdk_test.dir/src/c_sdk_test.cpp.i
.PHONY : src/c_sdk_test.cpp.i

src/c_sdk_test.s: src/c_sdk_test.cpp.s

.PHONY : src/c_sdk_test.s

# target to generate assembly for a file
src/c_sdk_test.cpp.s:
	$(MAKE) -f CMakeFiles/c_sdk_test.dir/build.make CMakeFiles/c_sdk_test.dir/src/c_sdk_test.cpp.s
.PHONY : src/c_sdk_test.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/odrive_test.dir/build.make CMakeFiles/odrive_test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/odrive_test.dir/build.make CMakeFiles/odrive_test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/odrive_test.dir/build.make CMakeFiles/odrive_test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/odrive_c_sdk.o: src/odrive_c_sdk.cpp.o

.PHONY : src/odrive_c_sdk.o

# target to build an object file
src/odrive_c_sdk.cpp.o:
	$(MAKE) -f CMakeFiles/odrive_c_sdk.dir/build.make CMakeFiles/odrive_c_sdk.dir/src/odrive_c_sdk.cpp.o
.PHONY : src/odrive_c_sdk.cpp.o

src/odrive_c_sdk.i: src/odrive_c_sdk.cpp.i

.PHONY : src/odrive_c_sdk.i

# target to preprocess a source file
src/odrive_c_sdk.cpp.i:
	$(MAKE) -f CMakeFiles/odrive_c_sdk.dir/build.make CMakeFiles/odrive_c_sdk.dir/src/odrive_c_sdk.cpp.i
.PHONY : src/odrive_c_sdk.cpp.i

src/odrive_c_sdk.s: src/odrive_c_sdk.cpp.s

.PHONY : src/odrive_c_sdk.s

# target to generate assembly for a file
src/odrive_c_sdk.cpp.s:
	$(MAKE) -f CMakeFiles/odrive_c_sdk.dir/build.make CMakeFiles/odrive_c_sdk.dir/src/odrive_c_sdk.cpp.s
.PHONY : src/odrive_c_sdk.cpp.s

src/odrive_cpp_sdk.o: src/odrive_cpp_sdk.cpp.o

.PHONY : src/odrive_cpp_sdk.o

# target to build an object file
src/odrive_cpp_sdk.cpp.o:
	$(MAKE) -f CMakeFiles/odrive_cpp_sdk.dir/build.make CMakeFiles/odrive_cpp_sdk.dir/src/odrive_cpp_sdk.cpp.o
.PHONY : src/odrive_cpp_sdk.cpp.o

src/odrive_cpp_sdk.i: src/odrive_cpp_sdk.cpp.i

.PHONY : src/odrive_cpp_sdk.i

# target to preprocess a source file
src/odrive_cpp_sdk.cpp.i:
	$(MAKE) -f CMakeFiles/odrive_cpp_sdk.dir/build.make CMakeFiles/odrive_cpp_sdk.dir/src/odrive_cpp_sdk.cpp.i
.PHONY : src/odrive_cpp_sdk.cpp.i

src/odrive_cpp_sdk.s: src/odrive_cpp_sdk.cpp.s

.PHONY : src/odrive_cpp_sdk.s

# target to generate assembly for a file
src/odrive_cpp_sdk.cpp.s:
	$(MAKE) -f CMakeFiles/odrive_cpp_sdk.dir/build.make CMakeFiles/odrive_cpp_sdk.dir/src/odrive_cpp_sdk.cpp.s
.PHONY : src/odrive_cpp_sdk.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... odrive_c_sdk"
	@echo "... odrive_cpp_sdk"
	@echo "... install/strip"
	@echo "... install"
	@echo "... c_sdk_test"
	@echo "... odrive_test"
	@echo "... src/c_sdk_test.o"
	@echo "... src/c_sdk_test.i"
	@echo "... src/c_sdk_test.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/odrive_c_sdk.o"
	@echo "... src/odrive_c_sdk.i"
	@echo "... src/odrive_c_sdk.s"
	@echo "... src/odrive_cpp_sdk.o"
	@echo "... src/odrive_cpp_sdk.i"
	@echo "... src/odrive_cpp_sdk.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

